-- Run once in the Supabase SQL editor for SPATS.
create table if not exists public.saved_models (
  id bigint generated by default as identity primary key,
  user_id text not null,
  name text not null,
  model_data jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id,name)
);
create index if not exists saved_models_user_id_idx on public.saved_models(user_id);

-- The SPATS server uses a secret service-role key. Do not expose this key client-side.
alter table public.saved_models enable row level security;
